global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-brokers'
    static_configs:
      - targets:
          - broker1:9094
          - broker2:9094
          - broker3:9094
    metrics_path: /metrics
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/certs/ca.crt
      cert_file: /etc/prometheus/certs/server.crt
      key_file: /etc/prometheus/certs/server.key
      insecure_skip_verify: false
